"""
ATT&CK Navigator layer builder — produces a v4.5-schema JSON layer file.

Navigator schema reference:
    https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4_5.md

Color coding (hot-gap layer):
    #ff6666 (red)   — active threat, NO Sigma detection → score 100 (critical)
    #66ff66 (green) — active threat, Sigma coverage exists → score 50
    (no entry)      — not observed in live feeds → not scored / gray in Navigator
"""
from datetime import datetime, timezone
from typing import Dict, List, Optional

from gap_analyzer.analyzer import GapResult


def build_navigator_layer(
    gap_result: GapResult,
    layer_name: str = "ATT&CK Coverage Heatmap — Active Threats vs Sigma",
    attck_version: str = "14",
    description: Optional[str] = None,
) -> dict:
    """
    Build an ATT&CK Navigator JSON layer (schema v4.5).

    The resulting JSON can be imported directly into:
        https://mitre-attack.github.io/attack-navigator/

    Args:
        gap_result:    Output of analyze_gaps().
        layer_name:    Human-readable layer name shown in Navigator.
        attck_version: ATT&CK version string (e.g. "14", "15", "18").
        description:   Optional layer description; auto-generated if None.

    Returns:
        Python dict representing the Navigator layer (call json.dumps() to serialize).
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    desc = description or f"Generated by attck-heatmap pipeline on {ts}"

    techniques: List[Dict] = []

    # Red — active threat, NO Sigma coverage (critical gaps)
    for tech_id in sorted(gap_result.gap_techniques):
        techniques.append(
            {
                "techniqueID": tech_id,
                "score": 100,
                "color": "#ff6666",
                "comment": "ACTIVE in threat feeds — NO Sigma detection rule",
                "enabled": True,
                "metadata": [{"name": "status", "value": "critical_gap"}],
                "showSubtechniques": False,
            }
        )

    # Green — active threat, Sigma coverage exists
    for tech_id in sorted(gap_result.covered_active):
        techniques.append(
            {
                "techniqueID": tech_id,
                "score": 50,
                "color": "#66ff66",
                "comment": "Active in threat feeds — Sigma rule exists",
                "enabled": True,
                "metadata": [{"name": "status", "value": "covered"}],
                "showSubtechniques": False,
            }
        )

    layer = {
        "name": layer_name,
        "versions": {
            "attack": attck_version,
            "navigator": "4.9",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": desc,
        "filters": {"platforms": ["Windows", "Linux", "macOS"]},
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "max",
            "showID": True,
            "showName": True,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#ff6666"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Active threat — NO detection (critical gap)", "color": "#ff6666"},
            {"label": "Active threat — covered by Sigma", "color": "#66ff66"},
        ],
        "metadata": [
            {"name": "generated_at", "value": ts},
            {"name": "attck_version", "value": attck_version},
            {"name": "total_active", "value": str(len(gap_result.active_techniques))},
            {"name": "total_gaps", "value": str(len(gap_result.gap_techniques))},
            {"name": "coverage_ratio", "value": f"{gap_result.coverage_ratio:.1%}"},
        ],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }
    return layer
